#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

echo "Current PATH: $PATH"
/usr/local/bin/npx lint-staged

# Ejecuta lint-staged
npx lint-staged

# Obtén la lista de archivos en staged que han sido añadidos, copiados, modificados o renombrados
staged_files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
formatted_files=""
max_length=0

# Encontrar la longitud del nombre de archivo más largo
for file in $staged_files; do
    if [ ${#file} -gt $max_length ]; then
        max_length=${#file}
    fi
done

# Muestra los archivos que están en el staged
echo "Los siguientes archivos se encuentran en el staged:"
for file in $staged_files; do
    spaces=$(($max_length - ${#file}))

    printf "🥑 %s%${spaces}s ( staged )\n" "$file"
done
